language: python
python:
    - "3.6"

#to install dependancies
install:
    - pip install -r requirements.txt

#to run tests
script:
    - nosetests test_api.py

#to run coverage tests
after_success:
    - coverage run --source='.' test_api.py
    - coveralls
cache:
    - pip
