language: python
python:
    - "3.6"

#to install dependancies
install:
    - pip install -r requirements.txt

#creating test_db
before_script:
    - psql -c 'create database test_db;' -U postgres

#to run tests
script:
    - nosetests tests

#to run coverage tests
after_success:
    - coverage run --source='.' --omit='run.py','manage.py' tests
    - coveralls
cache:
    - pip

notifications:
    email: false
