"""empty message

Revision ID: af561b4e13f9
Revises: 
Create Date: 2018-05-02 11:10:18.564342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af561b4e13f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('m_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('price', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=75), nullable=False),
    sa.Column('l_name', sa.String(length=75), nullable=False),
    sa.Column('u_name', sa.String(length=75), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('password', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('u_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('u_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('meals')
    # ### end Alembic commands ###
